config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get '/carers/:id/buy', to: 'carers#buy', as: :carers_buy
  get '/carers/you', to: 'carers#you'
  get '/carers/new', to: 'carers#new'
  get '/carers/', to: 'carers#index'  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  self.primary_key = :state
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carers_controller.rb
class CarersController < ApplicationController
    def index
    end
    def new
    end
    def buy
    end
    def you
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carers_helper.rb
module CarersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/carers/buy.html.erb
<div class="row">

  <div class="col-12 text-center mb-3">
    <h2 class="text-white">Encontramos o profissional ideal para <mark>você</mark>!</h2>
  </div>

  <div class="col-sm-7">
   <div class="card card-body mb-3">
    <h2>
      <strong>Assine</strong> o plano e <strong>reserve</strong> este profissional.
    </h2>

    <div class="row justify-content-center mt-3">
      <div class="col-auto">
        <div class="rounded-circle border enfermeiro"></div>
      </div>
      <div class="col-sm-6">
        <h1 class="mb-0">
        Fulano Fulano
        </h1>
        <p class="text-muted">especialista em enfermagem.</p> 
      </div>
    </div>

    <div class="row mt-4">
      <div class="col m-auto">
      <p class="text-center"><strong>Currículo</strong></p>
        <p>
          Sou cuidador e acompanhante de idosos!
          <br>
          Sou motorista tenho CNH categoria B
          <br>
          Tenho experiência de 10 anos e sou certificado pela Cematec com curso profissionalizante de cuidador e acompanhante de idosos.
          <br>
          Facilidade de adaptação, boa comunicação, organização, responsabilidade, fácil aprendizagem. Higiene pessoal do idoso em geral, banho, troca de fraldas, administrar medicações e etc, falo inglês e espanhol básico para atender idosos e pessoas de outras nacionalidades de todas as idades, tenho passaporte, disponibilidade de viajar para qualquer lugar do brasil e também para o exterior se for preciso como acompanhante, fico de acompanhante também em hospitais, clinicas, viagens, passeios, asilos e também posso trabalhar em residencias, posso fazer plantões e atendimentos em hospitais e residencias se houver a necessidade de 6, 12, 24, 36, 48, 72 hs, ou mais ou menos dias e horários a combinar, força física, e posso trabalhar também aos finais de semana e feriados, eu moro em são bernardo do campo SP mais eu atendo em qualquer região da grande são paulo, litoral, interior, outros estados e para o exterior também, já fiz viagens ao exterior, tenho experiência com translado casa, aeroporto, despachos de malas e check-in no embarque, posso dormir no local de trabalho e fazer viagens.
          <br>
          meus tels para contato 24hs
          <br>
          11 9 5841 58 77 cel tim e whatsaap.
          <br>
          11 9 4305 07 15 cel vivo
        </p>
      </div>
    </div>
  </div>

  </div>
  <div class="col-sm-5 m-auto">
  <div class="card card-body mb-3">
    <form class="mb-2">
        <div class="form-group">
          <label>Seu nome completo</label>
          <input type="text" class="form-control" placeholder="Nome">
        </div>
        <div class="form-group">
          <label>Seu melhor e-mail</label>
          <input type="email" class="form-control" placeholder="e-mail">
        </div>

        <div class="form-group text-center">
          <h3>
            <small>de <s>R$200</s>
            por </small>  <strong class="text-success">R$100</strong> 
            <small> na assinatura!</small>
          </h3>
        </div>

        <button type="submit" class="btn btn-success btn-block">Assinar agora!
          <strong>R$20/mês</strong>
        </button>
    </form>
  </div>
  <h2 class="text-white">Avaliações</h2>

    <% (0..2).to_a.each do |book| %>

      <div class="card mt-2">
        <div class="card-body">

          <div class="row">
            <div class="col-sm-2">
              <div class="rounded-circle border user"></div>
            </div>
            <div class="col">
              <strong>Usuário</strong> <br>
              <p class="text-muted">
                A minha avó gostou muito deste rapaz! Recomendo!
              </p>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/carers/index.html.erb
  <div class="row">
    <div class="col m-auto text-center">
      <h2 class="mb-3 text-white">Encontre o profissional <mark>ideal</mark> para seu ente querido.</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 m-auto">

    <% (0..10).to_a.each do |book| %>

      <div class="card mb-3">
        <div class="card-body">

          <div class="row">
            <div class="col-sm-2">
              <div class="rounded-circle border enfermeiro"></div>
            </div>
            <div class="col">
              <h1 class="mb-0">
                Fulano Fulano
              </h1>
              <p class="text-muted">especialista em enfermagem.</p>
            </div>
            <div class="col align-self-end text-right">
              <%= link_to "Requisitar", carers_buy_path(1), class: "btn btn-primary" %>
            </div>
          </div>

        </div>
      </div>
    <% end %>

      

    </div>

  </div>

app/views/carers/new.html.erb
<div class="row">
  <div class="col-sm-6 m-auto">
    <h3 class="mb-3 text-white">Cadastre-se agora e comece a trabalhar.</h3>
    <div class="card p-4">
      <form>
        <div class="form-group">
          <label>Seu nome completo</label>
          <input type="text" class="form-control" placeholder="Nome">
        </div>
        <div class="form-group">
          <label>Seu melhor e-mail</label>
          <input type="email" class="form-control" placeholder="e-mail">
        </div>

        <div class="form-group">
          <label>O que você faz?</label>
          <select class="form-control">
            <option>Enfermeiro(a)</option>
            <option>Cuidador(a)</option>
            <option>Fisioterapeuta</option>
          </select>
        </div>

        <div class="form-group">
          <label>Fale mais sobre a sua especialidade</label>
          <textarea class="form-control" placeholder="Conte-nos sobre você!"></textarea>
        </div>

        <div class="form-group">
          <label>Em que cidade?</label>
          <select class="form-control">
            <option>Palhoça, SC</option>
          </select>
        </div>

        <div class="form-group">
          <label>Qual bairro?</label>
          <input type="text" class="form-control" placeholder="Bairro">
        </div>

        <div class="form-group">
          <label>Quanto custa o seu plantão de 8 horas?</label>
          <input type="text" class="form-control" placeholder="R$">
        </div>

        <button type="submit" class="btn btn-success btn-block">
          <strong>Cadastrar</strong>
        </button>
      </form>

    </div>
  </div>

</div>

app/views/carers/you.html.erb
<div class="row">
  <div class="col-sm-6 m-auto">
    <h3 class="mb-3 text-white">Conte-nos mais sobre <mark>você</mark>.</h3>
    <div class="card p-4 mb-3">
      <form>

        <div class="form-group">
          <label>Seu nome completo</label>
          <input type="text" class="form-control" placeholder="Nome">
        </div>

        <div class="form-group">
          <label>Seu melhor e-mail</label>
          <input type="email" class="form-control" placeholder="e-mail">
        </div>
      </div>

      <h3 class="mb-3 text-white">Conte-nos mais sobre <mark>seu ente querido</mark>.</h3>

      <div class="card p-4">

        <div class="form-group">
          <label>Nome completo</label>
          <input type="text" class="form-control" placeholder="Nome">
        </div>

        <div class="form-group">
          <label>Sexo</label>
          <div class="radio">
            <label><input type="radio" name="optradio" checked> Masculino</label> <br>
            <label><input type="radio" name="optradio" checked> Feminino</label>
          </div>
        </div>

        <div class="form-group">
          <label>Estado de saúde</label>
          <textarea class="form-control" placeholder="Conte-nos sobre seu ente querido."></textarea>
        </div>

        <div class="form-group">
          <label>Condições de mobilidade</label>
          <textarea class="form-control"></textarea>
        </div>

        <div class="form-group">
          <label>Enfermidade diagnosticada</label>
          <textarea class="form-control"></textarea>
        </div>

         <div class="form-group">
          <label>Frequência de utilização de cuidados</label>
          <div class="radio">
            <label><input type="radio" name="optradio" checked> 2 vezes por semana</label> <br>
            <label><input type="radio" name="optradio" checked> 3 vezes por semana</label> <br>
            <label><input type="radio" name="optradio" checked> Finais de Semana</label> <br> 
            <label><input type="radio" name="optradio" checked> Diária</label> <br>
          </div>
        </div>

         <%= link_to "Buscar Profissionais", carers_buy_path(1), class: "btn btn-success btn-block" %>
      </form>

    </div>
  </div>

</div>

app/views/home/index.html.erb
<div class="row text-white justify-content-center mt-3">
  <div class="col-12 text-center mb-5">
    <h2>Encontre um <mark>Cuidador</mark>.</h2>
  </div>
    <div class="col-12 text-center mb-2">
    <h4> <strong>1º Passo:</strong>  <br>  
      Em que cidade você está?
    </h4>
  </div>
</div>

<div class="row justify-content-center text-center mt-2">
  <div class="col-6">
    <select class="form-control custom-select">
      <option>Palhoça, SC</option>
      <option>Pedra Branca, SC</option>
      <option>São José, SC</option>
      <option>Florianópolis, SC</option>
      <option>Biguaçu, SC</option>
    </select>
  </div>
  <div class="col-2">
    <%= link_to "Próximo", carers_you_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cuidadoso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-blue">
      <%= link_to root_path, class: "navbar-brand" do %>
        <strong>Cuidadoso</strong>
      <% end %>
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Requisitar um profissional", carers_path, class: "nav-link" %>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Sou cuidador", carers_new_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>